### ISSUE TITLE
サンプルデータについて

### ISSUE THREAD

**Issue by koji-k** [0918nobita/eitango_pretest#1]
wordsテーブルに格納するサンプルデータはありますか？

**Comment by 0918nobita** [comment]
1200レコードのサンプルがあります。Google Driveで共有します？

**Comment by koji-k** [comment]
サンプルデータとして、実際にsample.sqlのような名前でこのリポジトリ内にpushしておけば、他の人たちがこのプロジェクトを発見した時に、気軽にcloneして各自の端末でそのデータを使ってアプリケーション実行できるようになると思います。
なのでそれも素晴らしいプロジェクトの成果物なので公開しましょう :)

**Comment by 0918nobita** [comment]
了解です！
